version: '3'
services:
  backend:
    image: cnunodevs/server-siri:latest
    ports:
      - 14156:14156
    networks:
      - sirisys

  frontend:
    image: cnunodevs/siri-frontend:latest
    ports:
      - 4200:4200
    networks:
      - sirisys

networks:
  sirisys:
